// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"base_go_be/internal/controller"
	"base_go_be/internal/repo"
	"base_go_be/internal/service"
)

// Injectors from product.wire.go:

func InitProductRouterHandler() (*controller.ProductController, error) {
	iProductRepository := repo.NewProductRepository()
	iProductService := service.NewProductService(iProductRepository)
	productController := controller.NewProductController(iProductService)
	return productController, nil
}

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepository := repo.NewUserRepository()
	iUserService := service.NewUserService(iUserRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
