# curl  http://localhost:8001/v1/user/test
GET http://localhost:8001/v1/user/test

### local


# curl  http://localhost:8002/v1/user/test
GET http://localhost:8386/v1/user/test/1

### docker


# curl  http://localhost:8002/v1/user/list_user
GET http://localhost:8386/v1/user/list_user

### docker


# http://localhost:8386/v1/product/detail/2
GET http://localhost:8386/v1/product/detail/2

### docker


# http://localhost:8386/v1/product/list
GET http://localhost:8386/v1/product/list

### docker

http://localhost:8386/product/detail/2